import json
from pathlib import Path

path = Path('game.json')
data = json.loads(path.read_text(encoding='utf-8'))
layout = next(x for x in data['layouts'] if x.get('name') == 'FROST LAB')

# Version label.
build = next(o for o in layout['objects'] if o.get('name') == 'BuildText')
build['string'] = 'DEV v0.5.1'
build.setdefault('content', {})['text'] = 'DEV v0.5.1'

# Add explicit per-Actor wolf timers so a rescued FrozenWolfCandidate becomes
# an actually playable/acting second Wolf, not merely Role=Wolf data.
actor_obj = next(o for o in layout['objects'] if o.get('name') == 'Actor')
actor_vars = actor_obj.setdefault('variables', [])

def ensure_number_var(name, value=0):
    existing = next((v for v in actor_vars if v.get('name') == name), None)
    if existing is None:
        actor_vars.append({'name': name, 'type': 'number', 'value': value})
    else:
        existing['type'] = 'number'
        existing['value'] = value

ensure_number_var('AIWolfModeLeft', 0)
ensure_number_var('AIWolfCooldownLeft', 0)

OLD_GROUP = 'v0.5.0 CPU5 Rescue AI Phase 2'
NEW_GROUP = 'v0.5.1 CPU5 Rescue AI + Awakened Wolf Fix'
groups = [e for e in layout.get('events', []) if e.get('name') == OLD_GROUP]
if len(groups) != 1:
    raise RuntimeError(f'expected exactly one {OLD_GROUP!r}, got {len(groups)}')
group = groups[0]
group['name'] = NEW_GROUP

js = next(e for e in group['events'] if e.get('type') == 'BuiltinCommonInstructions::JsCode')
js['inlineCode'] = [
    "const dt = gdjs.evtTools.runtimeScene.getElapsedTimeInSeconds(runtimeScene);",
    "const vars = runtimeScene.getVariables();",
    "const gameOver = vars.get('GameOver').getAsBoolean();",
    "if (!gameOver) {",
    "  const players = runtimeScene.getObjects('Player');",
    "  const player = players.length ? players[0] : null;",
    "  if (player) {",
    "    const pVars = player.getVariables();",
    "    const pRole = pVars.get('Role').getAsString();",
    "    const pState = pVars.get('State').getAsString();",
    "    const playerWolfModeLeft = vars.get('WolfModeLeft').getAsNumber();",
    "    const px = player.getCenterXInScene();",
    "    const py = player.getCenterYInScene();",
    "    const actors = runtimeScene.getObjects('Actor');",
    "    const fleeRadius = 360;",
    "    const fleeSpeed = 155;",
    "    const wanderSpeed = 65;",
    "    const rescueSearchRadius = 520;",
    "    const rescueSpeed = 95;",
    "    const rescueDistance = 34;",
    "    const rescueDangerRadius = 360;",
    "    const aiWolfTriggerRadius = 420;",
    "    const aiWolfModeDuration = 5;",
    "    const aiWolfCooldownDuration = 5;",
    "    const aiWolfChaseSpeed = 175;",
    "    const aiWolfWanderSpeed = 65;",
    "    const aiWolfFreezeDistance = 30;",
    "",
    "    const activeHumanTargets = (wolfActor) => {",
    "      const targets = [];",
    "      if (pRole === 'Human' && pState === 'Active') targets.push(player);",
    "      for (const candidate of actors) {",
    "        if (candidate === wolfActor) continue;",
    "        const cv = candidate.getVariables();",
    "        if (cv.get('Role').getAsString() === 'Human' && cv.get('State').getAsString() === 'Active') targets.push(candidate);",
    "      }",
    "      return targets;",
    "    };",
    "",
    "    // Pass 1: make every Active Actor Wolf truly active. Outside WOLF MODE it",
    "    // wanders disguised as a white Human; when a Human is close it enters its",
    "    // own WOLF MODE, chases, and can freeze exactly one Human. It can never INFECT.",
    "    for (const wolf of actors) {",
    "      const wv = wolf.getVariables();",
    "      if (wv.get('Role').getAsString() !== 'Wolf' || wv.get('State').getAsString() !== 'Active') continue;",
    "      let modeLeft = Math.max(0, wv.get('AIWolfModeLeft').getAsNumber() - dt);",
    "      let cooldownLeft = Math.max(0, wv.get('AIWolfCooldownLeft').getAsNumber() - dt);",
    "      wv.get('AIWolfModeLeft').setNumber(modeLeft);",
    "      wv.get('AIWolfCooldownLeft').setNumber(cooldownLeft);",
    "      const wx = wolf.getCenterXInScene();",
    "      const wy = wolf.getCenterYInScene();",
    "      let target = null;",
    "      let targetDist = Infinity;",
    "      for (const human of activeHumanTargets(wolf)) {",
    "        const d = Math.hypot(human.getCenterXInScene() - wx, human.getCenterYInScene() - wy);",
    "        if (d < targetDist) { target = human; targetDist = d; }",
    "      }",
    "      if (modeLeft <= 0 && cooldownLeft <= 0 && target && targetDist <= aiWolfTriggerRadius) {",
    "        modeLeft = aiWolfModeDuration;",
    "        wv.get('AIWolfModeLeft').setNumber(modeLeft);",
    "      }",
    "      let vx = 0;",
    "      let vy = 0;",
    "      let speed = aiWolfWanderSpeed;",
    "      if (modeLeft > 0 && target) {",
    "        const tdx = target.getCenterXInScene() - wx;",
    "        const tdy = target.getCenterYInScene() - wy;",
    "        const td = Math.max(Math.hypot(tdx, tdy), 1);",
    "        vx = tdx / td;",
    "        vy = tdy / td;",
    "        speed = aiWolfChaseSpeed;",
    "        wolf.__iceWolfAIWolfTurnLeft = 0;",
    "        if (targetDist <= aiWolfFreezeDistance) {",
    "          target.getVariables().get('State').setString('Frozen');",
    "          wv.get('AIWolfModeLeft').setNumber(0);",
    "          wv.get('AIWolfCooldownLeft').setNumber(aiWolfCooldownDuration);",
    "          continue;",
    "        }",
    "      } else {",
    "        if (!Number.isFinite(wolf.__iceWolfAIWolfTurnLeft) || wolf.__iceWolfAIWolfTurnLeft <= 0 || !Number.isFinite(wolf.__iceWolfAIWolfDirX) || !Number.isFinite(wolf.__iceWolfAIWolfDirY)) {",
    "          const angle = Math.random() * Math.PI * 2;",
    "          wolf.__iceWolfAIWolfDirX = Math.cos(angle);",
    "          wolf.__iceWolfAIWolfDirY = Math.sin(angle);",
    "          wolf.__iceWolfAIWolfTurnLeft = 0.65 + Math.random() * 0.9;",
    "        }",
    "        wolf.__iceWolfAIWolfTurnLeft -= dt;",
    "        vx = wolf.__iceWolfAIWolfDirX;",
    "        vy = wolf.__iceWolfAIWolfDirY;",
    "      }",
    "      wolf.setX(Math.max(-708, Math.min(692, wolf.getX() + vx * speed * dt)));",
    "      wolf.setY(Math.max(-708, Math.min(692, wolf.getY() + vy * speed * dt)));",
    "    }",
    "",
    "    const visibleWolfThreat = (x, y) => {",
    "      let threat = null;",
    "      let best = Infinity;",
    "      if (pRole === 'Wolf' && pState === 'Active' && playerWolfModeLeft > 0) {",
    "        const d = Math.hypot(px - x, py - y);",
    "        if (d < best) { best = d; threat = { x: px, y: py, dist: d }; }",
    "      }",
    "      for (const candidate of actors) {",
    "        const cv = candidate.getVariables();",
    "        if (cv.get('Role').getAsString() !== 'Wolf' || cv.get('State').getAsString() !== 'Active' || cv.get('AIWolfModeLeft').getAsNumber() <= 0) continue;",
    "        const cx = candidate.getCenterXInScene();",
    "        const cy = candidate.getCenterYInScene();",
    "        const d = Math.hypot(cx - x, cy - y);",
    "        if (d < best) { best = d; threat = { x: cx, y: cy, dist: d }; }",
    "      }",
    "      return threat;",
    "    };",
    "",
    "    // Pass 2: Human wander/flee/rescue AI. Any visible Wolf (Player or awakened",
    "    // Actor Wolf) is treated as a threat only while that Wolf is in WOLF MODE.",
    "    for (const actor of actors) {",
    "      const actorVars = actor.getVariables();",
    "      const role = actorVars.get('Role').getAsString();",
    "      const state = actorVars.get('State').getAsString();",
    "      if (role !== 'Human' || state !== 'Active') continue;",
    "      actorVars.get('AIWolfModeLeft').setNumber(0);",
    "      actor.__iceWolfAIRescueCooldown = Math.max(0, (Number.isFinite(actor.__iceWolfAIRescueCooldown) ? actor.__iceWolfAIRescueCooldown : 0) - dt);",
    "      const ax = actor.getCenterXInScene();",
    "      const ay = actor.getCenterYInScene();",
    "      let vx = 0;",
    "      let vy = 0;",
    "      let speed = wanderSpeed;",
    "      let hasIntent = false;",
    "      const threat = visibleWolfThreat(ax, ay);",
    "      if (threat && threat.dist < fleeRadius) {",
    "        const safeDist = Math.max(threat.dist, 1);",
    "        vx = (ax - threat.x) / safeDist;",
    "        vy = (ay - threat.y) / safeDist;",
    "        speed = fleeSpeed;",
    "        hasIntent = true;",
    "        actor.__iceWolfAITurnLeft = 0;",
    "      } else if (actor.__iceWolfAIRescueCooldown <= 0) {",
    "        let rescueTarget = null;",
    "        let rescueTargetDist = Infinity;",
    "        for (const target of actors) {",
    "          if (target === actor) continue;",
    "          const targetState = target.getVariables().get('State').getAsString();",
    "          if (targetState !== 'Frozen' && targetState !== 'FrozenWolfCandidate') continue;",
    "          const tx = target.getCenterXInScene();",
    "          const ty = target.getCenterYInScene();",
    "          const td = Math.hypot(tx - ax, ty - ay);",
    "          if (td < rescueTargetDist && td <= rescueSearchRadius) { rescueTarget = target; rescueTargetDist = td; }",
    "        }",
    "        if (rescueTarget) {",
    "          const tx = rescueTarget.getCenterXInScene();",
    "          const ty = rescueTarget.getCenterYInScene();",
    "          const targetThreat = visibleWolfThreat(tx, ty);",
    "          const targetDanger = targetThreat && targetThreat.dist < rescueDangerRadius;",
    "          if (!targetDanger) {",
    "            if (rescueTargetDist <= rescueDistance) {",
    "              const targetVars = rescueTarget.getVariables();",
    "              const targetState = targetVars.get('State').getAsString();",
    "              if (targetState === 'FrozenWolfCandidate') {",
    "                targetVars.get('Role').setString('Wolf');",
    "                targetVars.get('State').setString('Active');",
    "                targetVars.get('AIWolfModeLeft').setNumber(0);",
    "                targetVars.get('AIWolfCooldownLeft').setNumber(1.5);",
    "                actorVars.get('State').setString('Frozen');",
    "              } else if (targetState === 'Frozen') {",
    "                targetVars.get('State').setString('Active');",
    "                actor.__iceWolfAIRescueCooldown = 1.0;",
    "                rescueTarget.__iceWolfAIRescueCooldown = 1.2;",
    "              }",
    "              continue;",
    "            }",
    "            const safeRescueDist = Math.max(rescueTargetDist, 1);",
    "            vx = (tx - ax) / safeRescueDist;",
    "            vy = (ty - ay) / safeRescueDist;",
    "            speed = rescueSpeed;",
    "            hasIntent = true;",
    "            actor.__iceWolfAITurnLeft = 0;",
    "          }",
    "        }",
    "      }",
    "      if (!hasIntent) {",
    "        if (!Number.isFinite(actor.__iceWolfAITurnLeft) || actor.__iceWolfAITurnLeft <= 0 || !Number.isFinite(actor.__iceWolfAIDirX) || !Number.isFinite(actor.__iceWolfAIDirY)) {",
    "          const angle = Math.random() * Math.PI * 2;",
    "          actor.__iceWolfAIDirX = Math.cos(angle);",
    "          actor.__iceWolfAIDirY = Math.sin(angle);",
    "          actor.__iceWolfAITurnLeft = 0.65 + Math.random() * 0.9;",
    "        }",
    "        actor.__iceWolfAITurnLeft -= dt;",
    "        vx = actor.__iceWolfAIDirX;",
    "        vy = actor.__iceWolfAIDirY;",
    "      }",
    "      actor.setX(Math.max(-708, Math.min(692, actor.getX() + vx * speed * dt)));",
    "      actor.setY(Math.max(-708, Math.min(692, actor.getY() + vy * speed * dt)));",
    "    }",
    "  }",
    "}",
]

# Wall/barrier separation and outer bounds now apply to every Active Actor,
# including the awakened Actor Wolf. Frozen actors still do not move.
fe = next(e for e in group['events'] if e.get('type') == 'BuiltinCommonInstructions::ForEach' and e.get('object') == 'Actor')
fe['conditions'] = [
    {'type': {'value': 'BooleanVariable'}, 'parameters': ['GameOver', 'False', '']},
    {'type': {'value': 'StringObjectVariable'}, 'parameters': ['Actor', 'State', '=', '\"Active\"']},
]

# Extend the guaranteed solid-color renderer: awakened Wolf stays visually hidden
# (white) outside its own WOLF MODE, and becomes dark red only while mode is active.
visual_group = next(e for e in layout['events'] if e.get('name') == 'v0.3.4 guaranteed solid-state visuals')
visual_js = next(e for e in visual_group['events'] if e.get('type') == 'BuiltinCommonInstructions::JsCode')
visual_js['inlineCode'] = [
    "const sceneVars = runtimeScene.getVariables();",
    "const wolfModeLeft = sceneVars.get('WolfModeLeft').getAsNumber();",
    "const getState = (obj) => obj.getVariables().get('State').getAsString();",
    "const ensureSolidMaterials = (obj) => {",
    "  const mesh = obj.get3DRendererObject && obj.get3DRendererObject();",
    "  if (!mesh) return null;",
    "  if (!obj.__iceWolfSolidVisualReady) {",
    "    const oldMaterials = Array.isArray(mesh.material) ? mesh.material : [mesh.material];",
    "    const solidMaterials = oldMaterials.map(() => new THREE.MeshBasicMaterial({ color: 0xffffff }));",
    "    mesh.material = Array.isArray(mesh.material) ? solidMaterials : solidMaterials[0];",
    "    obj.__iceWolfSolidVisualReady = true;",
    "  }",
    "  return Array.isArray(mesh.material) ? mesh.material : [mesh.material];",
    "};",
    "const setSolidColor = (obj, hexColor) => {",
    "  const materials = ensureSolidMaterials(obj);",
    "  if (!materials) return;",
    "  for (const material of materials) material.color.setHex(hexColor);",
    "};",
    "for (const actor of runtimeScene.getObjects('Actor')) {",
    "  const av = actor.getVariables();",
    "  const state = av.get('State').getAsString();",
    "  const role = av.get('Role').getAsString();",
    "  const aiWolfModeLeft = av.get('AIWolfModeLeft').getAsNumber();",
    "  const isFrozen = state === 'Frozen' || state === 'FrozenWolfCandidate';",
    "  if (isFrozen) setSolidColor(actor, 0xff0000);",
    "  else if (role === 'Wolf' && aiWolfModeLeft > 0) setSolidColor(actor, 0x8b0000);",
    "  else setSolidColor(actor, 0xffffff);",
    "}",
    "for (const player of runtimeScene.getObjects('Player')) {",
    "  const state = getState(player);",
    "  if (state === 'Frozen') setSolidColor(player, 0xff0000);",
    "  else if (wolfModeLeft > 0) setSolidColor(player, 0x8b0000);",
    "  else setSolidColor(player, 0xffffff);",
    "}",
]

path.write_text(json.dumps(data, ensure_ascii=False, separators=(',', ':')), encoding='utf-8')
print('v0.5.1 awakened Wolf fix applied')
